/* SAS Module 3 */


/*
 * LIBNAME SETUP
 * Update the path below to your local project data directory.
 * All SAS datasets (.sas7bdat) are located in the /data folder
 * at the root of this repository.
 *
 * Example (Windows): libname phdata 'C:\Users\YourName\sas-public-health-analytics\data';
 * Example (Unix/Mac): libname phdata '/home/yourname/sas-public-health-analytics/data';
 */
libname phdata './data';

/* Notes Section 3.1 */ 

PROC SORT DATA = phdata.PHASE2;
	BY STUDYID;
RUN;

PROC SORT DATA = phdata.LABS;
	BY STUDYID;
RUN;

DATA P2WLABS;
	MERGE phdata.PHASE2 phdata.LABS;
	BY STUDYID;
RUN;

PROC PRINT DATA= P2WLABS;
RUN;

PROC SORT DATA = phdata.PHASE2;
	BY STUDYID;
RUN;

PROC SORT DATA = phdata.LABS;
	BY STUDYID;
RUN;

DATA P2WLABS2;
	MERGE phdata.PHASE2(IN=A) phdata.LABS;
	BY STUDYID;
		IF A;
RUN;

PROC PRINT DATA= P2WLABS2;
RUN;

/* Notes Section 3.2 */ 

DATA WALKDEAD;
INPUT @1 STUDYID @6 FNAME $16. @23 LNAME $10. @33 SEX @35 NUMEPIS @38 SHOW $20.;
DATALINES;
1001 RICK             GRIMES    1 115 THE WALKING DEAD
1002 CARL             GRIMES    1 115 THE WALKING DEAD
1003 DARYL            DIXON     1 113 THE WALKING DEAD
1004 CAROL            PELETIER  2 112 THE WALKING DEAD
1005 MAGGIE           GREENE    2 108 THE WALKING DEAD
1006 MICHONNE         .         2 96  THE WALKING DEAD
1007 GLENN            RHEE      1 81  THE WALKING DEAD
1008 TARA             CHAMBLER  2 71  THE WALKING DEAD
1009 SASHA            WILLIAMS  2 69  THE WALKING DEAD
1010 EUGENE           PORTER    1 68  THE WALKING DEAD
1011 ROSITA           ESPINOSA  2 68  THE WALKING DEAD
1012 GABRIEL          STOKES    1 63  THE WALKING DEAD
1013 AARON            .         1 54  THE WALKING DEAD
1014 MORGAN           JONES     1 53  THE WALKING DEAD
1015 BETH             GREENE    2 51  THE WALKING DEAD
1016 ABRAHAM          FORD      1 38  THE WALKING DEAD
1017 HERSHEL          GREENE    1 38  THE WALKING DEAD
1018 DWIGHT           .         1 36  THE WALKING DEAD
1019 LORI             GRIMES    2 36  THE WALKING DEAD
1020 ANDREA           HARRISON  2 35  THE WALKING DEAD
;
RUN;

DATA GOT;
INPUT @1 STUDYID @6 FNAME $16. @23 LNAME $10. @33 SEX @35 NUMEPIS @38 SHOW $20.;
DATALINES;
5001 TYRION           LANNISTER 1 61 GAME OF THRONES
5002 CERSEI           LANNISTER 2 58 GAME OF THRONES
5003 DAENERYS         TARGARYEN 2 56 GAME OF THRONES
5004 JON              SNOW      1 56 GAME OF THRONES
5005 SANSA            STARK     2 54 GAME OF THRONES
5006 ARYA             STARK     2 53 GAME OF THRONES
5007 JAIME            LANNISTER 1 49 GAME OF THRONES
5008 JORAH            MORMONT   1 48 GAME OF THRONES
5009 THEON            GREYJOY   1 43 GAME OF THRONES
5010 SAMWELL          TARLY     1 43 GAME OF THRONES
5011 PETYR            BAELISH   1 41 GAME OF THRONES
5012 LORD             VARYS     1 41 GAME OF THRONES
5013 BRIENNE OF TARTH .         2 37 GAME OF THRONES
5014 DAVOS            SEAWORTH  1 36 GAME OF THRONES
5015 BRAN             STARK     1 35 GAME OF THRONES
5016 BRONN            .         1 34 GAME OF THRONES
5017 MISSANDEI        .         2 34 GAME OF THRONES
5018 SANDOR           CLEGANE   1 33 GAME OF THRONES
5019 GRAND MAESTER    PYCELLE   1 31 GAME OF THRONES
5020 EDDISON          TOLLETT   1 30 GAME OF THRONES
;
RUN;

DATA ACTORS;	
INPUT @1 STUDYID @6 ACTOR $25. ;
DATALINES;
1001 ANDREW LINCOLN
1002 CHANDLER RIGGS
1003 NORMAN REEDUS
1004 MELISSA MCBRIDE
1005 LAUREN COHAN
1006 DANAI GURIRA
1007 STEVEN YEUN
1008 ALANNA MASTERSON
1009 SONEQUA MARTIN-GREEN
1010 JOSH MCDERMITT
1011 CHRISTIAN SERRATOS
1012 SETH GILLIAM
1013 ROSS MARQUAND
1014 LENNIE JAMES
1015 EMILY KINNEY
1016 MICHAEL CUDLITZ
1017 SCOTT WILSON
1018 AUSTIN AMELIO
1019 SARAH WAYNE CALLIES
1020 LAURIE HOLDEN
5001 PETER DINKLAGE
5002 LENA HEADEY
5003 EMILIA CLARKE
5004 KIT HARRINGTON
5005 SOPHIE TURNER
5006 MAISIE WILLIAMS
5007 NIKOLAJ COSTER-WALDAU
5008 IAIN GLEN
5009 ALFIE ALLEN
5010 JOHN BRADLEY
5011 AIDAN GILLEN
5012 CONLETH HILL
5013 GWENDOLINE CHRISTIE
5014 LIAM CUNNINGHAM
5015 ISAAC HEMPSTEAD WRIGHT
5016 JEROME FLYNN
5017 NATHALIE EMMANUEL
5018 RORY MCCANN
5019 JULIAN GLOVER
5020 BEN CROMPTON
8001 BRYSHERE GRAY
8002 JUSSIE SMOLLETT
8003 TERRENCE HOWARD
8004 TARAJI P HENSON
8005 GABOUREY SIDIBE
;
RUN;

/* 3.2 A */ 

DATA WD_GOT;
	SET WALKDEAD GOT;
RUN;

/* 3.2 B */ 

PROC SORT DATA = WD_GOT;
	BY STUDYID;
RUN; 

PROC SORT DATA = ACTORS;
	BY STUDYID;
RUN;

DATA WDGOT_A;
		MERGE WD_GOT ACTORS;
		BY STUDYID;
RUN;

PROC PRINT DATA= WDGOT_A NOOBS; RUN;

/* 3.2 C */ 

PROC SORT DATA = WD_GOT;
		BY STUDYID;
RUN; 

PROC SORT DATA = ACTORS;
		BY STUDYID;
RUN; 

DATA WDGOT_B;
		MERGE WD_GOT (IN=CHAR) ACTORS;     
		BY STUDYID;
		IF CHAR;	
RUN;

PROC PRINT DATA= WDGOT_B NOOBS; RUN;

/* 3.2 D */ 

PROC SORT DATA = WD_GOT;
		BY STUDYID;
RUN; 

PROC SORT DATA = ACTORS;
		BY STUDYID;
RUN; 
	
DATA WDGOT_C;
		MERGE WD_GOT (IN=CHAR) ACTORS (IN=ACT);     
		BY STUDYID;
		IF ACT AND ^CHAR;	
RUN;

PROC PRINT DATA= WDGOT_C NOOBS; RUN;

/* 3.2 E */ 

PROC SORT DATA = WD_GOT;
	BY STUDYID;
RUN; 

PROC SORT DATA = ACTORS;
	BY STUDYID;
RUN; 

DATA WDGOT_D;
	MERGE WD_GOT (IN=CHAR) ACTORS (IN=ACT);
	BY STUDYID;

	IF ACT AND ^CHAR THEN SHOW = "EMPIRE";   

RUN;

PROC PRINT DATA= WDGOT_D NOOBS; RUN; 

/* Notes Section 3.3 */ 

DATA ONE;
	SET ACTORS (OBS=10);
RUN;

PROC PRINT DATA = ONE;
	TITLE 'CREATING A NEW SAS DATA SET FROM AN ORIGINAL SAS DATA SET';
RUN;

PROC PRINT DATA = ONE;
	TITLE;
RUN;

DATA TWO (KEEP = STUDYID SEX NUMEPIS);
	SET WALKDEAD;
RUN;

PROC PRINT DATA = TWO;
RUN;

DATA TWO (DROP = SHOW);
	SET WALKDEAD;
RUN;

PROC PRINT DATA = TWO;
RUN;

DATA TWO   (KEEP = STUDYID FNAME LNAME) 
     THREE (KEEP = STUDYID SEX NUMEPIS SHOW);
SET WALKDEAD;
RUN;

PROC PRINT DATA = TWO;
	TITLE NAME;
RUN;

PROC PRINT DATA = THREE;
	TITLE OTHER INFO;
RUN;

PROC FREQ DATA=WALKDEAD;
	TABLES SEX;
RUN;

DATA FOUR;
	SET WALKDEAD;
	IF SEX=1;
RUN;

DATA FIVE;
	SET WALKDEAD;
	IF SEX=1 & NUMEPIS < 60;
RUN;

DATA SIX;
	SET WALKDEAD;
	IF NUMEPIS > 100 THEN DELETE;
RUN;

PROC FREQ DATA=WALKDEAD;
	TABLES LNAME;
	WHERE SEX=2;
RUN;

/* Notes Section 3.4 */ 

PROC FREQ DATA=phdata.mod3lab;
RUN;

PROC FREQ DATA=phdata.mod3lab;
	TABLES CALORIE;
RUN;

PROC PRINT DATA=phdata.mod3lab;
	WHERE 0 < CALORIE < 1000;
RUN;

DATA TEMP;
	SET phdata.mod3lab;

		IF STUDYID = 268 THEN PLANE=1;
		IF STUDYID = 268 THEN CALORIE=2500;
		IF STUDYID = 268 THEN FRUIT=5;
		IF STUDYID = 268 THEN VITAMIN=.;

		IF STUDYID = 286 THEN DO; *This illustrates use of a do-loop;
		   WTTYPE = ' ';  *Remember that this is a character variable;
		   SMOKE = 0;
		   SLEEP = 6;
		   PLANE = 1;
		   CALORIE = 1500;
		   FRUIT = 8;
		   VITAMIN = .;
		END;

		IF STUDYID=306 OR STUDYID=347 THEN CALORIE=.;
RUN;

PROC PRINT DATA=TEMP;
	WHERE STUDYID IN (268, 286, 306, 347); 
RUN;

/* Notes Section 3.5 */ 

PROC FREQ DATA=TEMP;
	TABLES SEX MARITAL;
RUN;

DATA TEMP2;
   SET TEMP;

      IF SEX = 'female' OR SEX = 'FEMALE' THEN SEX1 = 1;
      IF SEX = 'male' OR SEX = 'MALE' THEN SEX1 = 0;

	  IF MARITAL = 'single' OR MARITAL = 'SINGLE' OR MARITAL = 'Single' THEN MARITAL1 = 1;
	  IF MARITAL = 'married' OR MARITAL = 'MARRIED' THEN MARITAL1 = 0;

RUN;

PROC FREQ DATA = TEMP2;
   TABLES SEX SEX1 MARITAL MARITAL1;
RUN;

PROC FREQ DATA = TEMP2;
	TABLES SEX*SEX1 MARITAL*MARITAL1;
	TITLE CROSSTABS OF OLD AND NEW VARIABLES;
RUN;

/* MOD 3 #1 */
	/*a*/
data wdgot_e;
set wdgot_d;

if studyid = 8001 then do;
fname = "HAKEEM";
lname = "LYON";
end;
if studyid = 8002 then do;
fname = "JAMAL";
lname = "LYON";
end;
if studyid = 8003 then do;
fname = "LUCIOUS";
lname = "LYON";
end;
if studyid = 8004 then do;
fname = "COOKIE";
lname = "LYON";
end;
if studyid = 8005 then do;
fname = "BECKY";
lname = "WILLIAMS";
end;

	/*b*/
if studyid in (8001, 8002, 8003) then SEX = 1;

	/*c*/
if studyid = 8004 | studyid = 8005 then SEX = 2;

	/*d*/
if ACTOR in ("BRYSHERE GRAY", "JUSSIE SMOLLETT", "TERRENCE HOWARD", "TARAJI P HENSON") then NUMEPIS = 49;

if ACTOR = "GABOUREY SIDIBE" then NUMEPIS = 45;

run;

/* MOD 3 #2 */
DATA TEMPF;
SET TEMP2;
/*a*/ IF WEIGHT=43 THEN WEIGHT=143;
/*b*/ IF HEIGHTFT LT 4 OR HEIGHTFT GT 6 THEN HEIGHTFT=.;
/*c*/
IF BIRTHOZ=16 THEN DO;
BIRTHOZ=0;
BIRTHLB = BIRTHLB+1;
END;
IF BIRTHOZ GT 16 THEN BIRTHOZ=.;
/*d*/ IF HOUSE GT 7 THEN HOUSE=.;
/*e*/
IF WTTYPE = 'ideal' OR WTTYPE = 'IDEAL' OR WTTYPE = 'Ideal' THEN WTTYPE1 = 0;
IF WTTYPE = 'under' OR WTTYPE = 'UNDER' THEN WTTYPE1 = 1;
IF WTTYPE = 'over' OR WTTYPE = 'OVER' THEN WTTYPE1 = 2;
RUN;

/* MOD 3 #3 */
DATA TEMPG;
SET TEMPF(OBS=100);
RUN;

/* MOD 3 #4 */
DATA TEMPH(DROP=SLEEP PLANE FRUIT);
SET TEMPF;
RUN;

/* MOD 3 #5 */
DATA TEMPI;
SET TEMPF;
IF PLANE=0;
RUN;
